default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: michael # role previously added
  password: <%= ENV['DATABASE_PASSWORD'] %> # variable previously added

development:
  <<: *default
  database: odinbook_development

test:
  <<: *default
  database: odinbook_test

production:
  <<: *default
  database: odinbook_production
